language: python
python:
  - "2.7"
  - "3.6"
install:
- pip install coveralls requests requests_mock
script: coverage run --source viper-metascan/metascan/ -m py.test tests -v
after_success:
  coveralls
